sudo: false
language: node_js
services:
  - mongodb
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '6'
  - '5'
before_script:
  - sleep 15
script:
  - yarn test
after_script:
  - yarn run coveralls
