sudo: false
language: node_js
services:
  - mongodb
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
before_script:
  - sleep 15
script:
  - yarn test
after_script:
  - yarn run coveralls
